import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { prisma } from "../server/db/client";
import Image from "next/image";
import Link from "next/link";
import { motion } from "framer-motion"

export const getStaticProps: GetStaticProps = async (context) => {

  const data = await prisma.category.findMany();
  // transform data to JSON
  const categories = JSON.parse(JSON.stringify(data));
  console.log(categories);

  return {
    props: {
      categories,
    }, // will be passed to the page component as props
  };
}

type Props = {
  categories: [
    {
      id: number;
      name: string;
      slug: string;
      image: string;
    }
  ];
};

const Home: NextPage<Props> = ({ categories }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col md:flex-row items-center justify-evenly gap-2">
        {/* map thru the products */}
        {categories && categories.map((category) => (
          <Link href={'/category/' + category.id} key={category.id}><motion.div className="flex flex-col items-center justify-center border-2 border-white rounded-lg"
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.5, duration: 1.5, type: "spring" }}
          >
            <h1 className="text-2xl">{category.name}</h1>
            <Image src={category.image} width={370} height={370} alt={category.name} priority />
          </motion.div></Link>
        ))}
      </main>
    </>
  );
};

export default Home;
