import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { prisma } from "../server/db/client";
import Image from "next/image";

export const getServerSideProps: GetServerSideProps = async (context) => {

  const data = await prisma.product.findMany();
  // transform data to JSON
  const products = JSON.parse(JSON.stringify(data));
  console.log(products);

  return {
    props: {
      products,
    }, // will be passed to the page component as props
  };
}

type Props = {
  products: [
    {
      id: number;
      name: string;
      price: number;
      createdAt: string;
      image: string;
    }
  ];
};

const Home: NextPage<Props> = ({ products }) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col md:flex-row items-center justify-evenly">
        {/* map thru the products */}
        {products && products.map((product) => (
          <div key={product.id} className="flex flex-col items-center justify-center border-2 border-white rounded-lg">
            <h1 className="text-2xl">{product.name}</h1>
            <h1 className="text-2xl">{product.price}</h1>
            <Image src={product.image} width={160} height={160} alt={product.name} />
          </div>
        ))}
      </main>
    </>
  );
};

export default Home;
